# Generated by Django 4.1 on 2022-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
