# Generated by Django 4.1 on 2022-09-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_attendance_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
