# Generated by Django 4.1 on 2022-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_attendance_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
