# Generated by Django 4.1 on 2022-09-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_attendance_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
