# Generated by Django 4.1 on 2022-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
