# Generated by Django 4.1 on 2022-09-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_delete_manager_employee_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='request',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.CharField(blank=True, default='Absent', max_length=10, null=True),
        ),
    ]
